### ISSUE TITLE
R chunk as a trigger?

### ISSUE THREAD

**Issue by trangdata** [qmd-lab/closeread#156]
Awesome package! 🚀 

I'm currently working on my closeread submission and have a quick question: Is there a way for an R chunk to trigger a sticky? In the example below, I would like the first chunk `weight` to trigger the plot in `mpg`. I think currently the new line between `@cr-mpg` prevents the first R chunk to become an actual trigger. I have tried moving `@cr-mpg` before the chunk starts as well but that didn't work either. Am I missing something obvious?

```` markdown
---
title: My First Closeread
format: closeread-html
---

Hello World!

::::{.cr-section}

```{r weight}
library(ggplot2)
ggplot(mtcars, aes(x = wt, y = qsec)) +
  geom_point() +
  labs(title = "Plot 1: I want this to trigger Plot 2")
```
@cr-mpg

:::{#cr-mpg}
```{r mpg}
ggplot(mtcars, aes(x = mpg, y = hp)) +
  geom_point() +
  labs(title = "Plot 2: Sticky")
```

:::

::::
````

**Comment by jimjam-slam** [comment]
Hey @trangdata! There's an [alternate block syntax](https://closeread.dev/guide/components.html#triggers) you can use for triggers that'll let you do this. Instead of using a citation after your R chunk, you'll want to wrap your R chunk in a fenced div and provide the ID of the sticky as the `focus-on` attribute, like so:

````
Hello World!

::::{.cr-section}

:::{focus-on="cr-mpg"}
```{r weight}
library(ggplot2)
ggplot(mtcars, aes(x = wt, y = qsec)) +
  geom_point() +
  labs(title = "Plot 1: I want this to trigger Plot 2")
```
:::

<!-- your other stuff here -->
````

Let us know how you go with that!

**Comment by trangdata** [comment]
Ah exactly what I was looking for. This makes sense! Sorry I missed it in the documentation. 🙏🏽

**Comment by jimjam-slam** [comment]
No worries at all, @trangdata — good luck with your entry! 🥳
