### ISSUE TITLE
Changing image panning speed

### ISSUE THREAD

**Issue by axkent** [qmd-lab/closeread#160]
How could I slow down image panning speed? I'd like to pan to one side of the image and then to the opposite side. It moves quicker than I'd like it to. 

`[@cr-launchplot_full_static]{pan-to="715px"}`
`[@cr-launchplot_full_static]{pan-to="-825px"}`

**Comment by jimjam-slam** [comment]
Hi @axkent! You can override the transition speed with CSS. For example, this CSS (included as a [raw HTML block](https://quarto.org/docs/authoring/markdown-basics.html#raw-content)) makes all stickies transition over two seconds (as opposed to the one second default):

````
```{=html}
.sticky {
  transition-duration: 2s
}
```
````

If you'd like to change the speed for particular stickies, you can use their ID (prefixed with a `#`) instead of `.sticky`.
