### ISSUE TITLE
Bug in vertical alignment of triggers when using hotkeys?

### ISSUE THREAD

**Issue by gkaramanis** [qmd-lab/closeread#84]
Not sure if this is really a bug but I would expect the trigger to be vertically aligned when using the hotkeys for scrolling. Sometimes the triggers are aligned at the top but, for me at least, most of them get cut-off:

<img width="1840" alt="Screenshot 2024-08-19 at 14 34 20" src="https://github.com/user-attachments/assets/fb214732-7680-4fac-a1fc-f875feb40eca">

**Comment by andrewpbray** [comment]
This is this intended behavior though I agree there's improvements that could be made here!

If you look at the css, it adjust how the narrative blocks are laid out:

https://github.com/qmd-lab/closeread/blob/2ec55c9b3c689850fe534404b58a9d20a20e4031/docs/gallery/examples/minards-map/cr-tufte.css#L61-L64

So the paragraphs are at the very top of the trigger block. If you look at the base css for trigger blocks, the padding is equally spread between top and bottom by using `padding-block`:

https://github.com/qmd-lab/closeread/blob/2ec55c9b3c689850fe534404b58a9d20a20e4031/_extensions/closeread/closeread.css#L16-L19

You can see this more clearly if you modify the minard example to include `debug-mode: true` in the yaml (something that in time I'd like to shift to a hotkey). The WH Auden example, by contrast, works just fine using the hotkeys to skip to next trigger since it doesn't change the default trigger padding.

Those changes to the default trigger padding in the minard example was a short term solution to a more general use case of wanting slightly different behavior on the first trigger block in the section. I think we can solve this more intelligently (but introducing a "spacer block"), but I think that should probably happen after we implement #54 . I've made a note of it in that thread so that we don't lose track of it.

Thanks for the issue!

**Comment by gkaramanis** [comment]
Thank you for the detailed explanation!
