### ISSUE TITLE
Consider changing closeread from a custom format to a filter

### ISSUE THREAD

**Issue by andrewpbray** [qmd-lab/closeread#93]
This would allow users to develop their own closeread templates.

**Comment by jimjam-slam** [comment]
The only real work doing this, I think, is in inlining the core CSS straight into the HTML page!

**Comment by andrewpbray** [comment]
What are your thoughts on this?

https://github.com/quarto-dev/quarto-cli/discussions/10789

That suggests that there is a decent workflow for someone to make a custom format out of closeread-html even if we structure it as a custom format.

**Comment by jimjam-slam** [comment]
Yeah, I've been thinking on this! I don't love that workflow, tbh, because it places the onus on the user to stitch the fields from all the relevant extensions together, ensure extension paths resolve properly, etc.

If we can continue to contain Closeread to a filter (since we use the Quarto Pandoc API to add the JS during the filter and could potentially inline the CSS using the filter), I feel like filters are far more composable than custom formats. I'm not married to it, though!

**Comment by jimjam-slam** [comment]
Discussed pros and cons of switching from a custom format to just a filter:

**Pros:**

+ Filters are more composable

**Cons**:

- Existing Closeread config options would have to move
- Can't run the same format off twice with different options, we think (eg. `html` twice but once with the filter)

**Comment by jimjam-slam** [comment]
Left as a format for now, but might review in the future!
